language: node_js

node_js:
- "10"

sudo: true

services:
- docker
- redis-server
- postgresql

before_install:
- echo Entering before install stage ...
- sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass '123abc456'
- psql -c 'create database travis_ci_test;' -U postgres

install:
- echo Entering install stage ...
- yarn install
- yarn test

script:
- echo Entering execution stage ...
- yarn coverage
- echo Pushing the Docker images ...
- ./scripts/build_docker_images.sh
