language: node_js

node_js:
- "8"
- "10"
- "11"
- "12"

sudo: true

services:
- docker
- redis-server
- postgresql

before_install:
- echo Entering before install stage ...
- sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass '123abc456'
- psql -c 'create database travis_ci_test;' -U postgres
- cp ci /authenticator-init

install:
- echo Entering install stage ...
- yarn install

script:
- echo Entering execution stage ...
- yarn test

before_deploy:
- echo Entering before deployment stage ...
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- ./scripts/build_docker_image.sh

deploy:
- provider: script
  skip_cleanup: true
  script: yarn coverage
  on:
    all_branches: true
    node_js: '10'
- provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy_hash_version_to_docker.sh
  on:
    all_branches: true
    node_js: '10'
- provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy_stable_versions_to_docker.sh
  on:
    branch: master
    node_js: '10'