version: '3.7'
services:
  api:
    container_name: sloth_authenticator_api
    restart: always
    build: .
    ports:
      - ${CONTAINER_PUBLIC_PORT}:${APP_PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: sloth_authenticator_pg
    restart: always
    build: database
    env_file:
      - .env
    volumes:
      - ~/.volumes/sloth_authenticator/postgres:/var/lib/postgresql/data
  pgadmin:
    image: fenglc/pgadmin4:python2.7-alpine
    container_name: sloth_authenticator_pgadmin
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    environment:
      DEFAULT_USER: 'admin'
      DEFAULT_PASSWORD: 'admin'
  redis:
    container_name: sloth_authenticator_redis
    image: redis:5.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ~/.volumes/sloth_authenticator/redis:/data
