version: '3.7'
services:
  auth_service:
    container_name: auth_service_api
    restart: always
    build: .
    ports:
      - ${CONTAINER_PUBLIC_PORT}:${APP_PORT}
    environment:
      TZ: America/Mazatlan
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: auth_service_pg
    restart: always
    build: database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
  pgadmin:
    image: fenglc/pgadmin4:python2.7-alpine
    container_name: auth_service_pgadmin
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    environment:
      DEFAULT_USER: 'admin'
      DEFAULT_PASSWORD: 'admin'
  redis:
    container_name: auth_service_redis
    image: redis:5.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
