service:
  - name: crawlerApi
    user: sloth_crawler
    password: 12345678
  - name: emailSenderApi
    user: sloth_mailer
    password: 87654321
clientTypes:
  crawlerApi:
    - api
    - frontEnd
  emailSenderApi:
    - mailer
accessPrivileges:
  crawlerApi:
    - start
    - listJobs
  emailSenderApi:
    - send
    - massSend
    - read
accessPrivilegesPerUserType:
  crawlerApi:
    api:
      - start
      - listJobs
    frontEnd:
      - listJobs
  emailSenderApi:
    mailer:
      - send
      - massSend
      - read
clients:
  crawlerApi:
    - slothens:
        name: slothens
        user: slothens
        password: abc
    - sirSlothsAlot:
        name: sirSlothsAlot
        user: sirSlothsAlot
        password: cba
  emailSenderApi:
    - slothyMail:
        name: slothyMail
        user: slothyMail
        password: 123